const SUPABASE_URL = 'https://xspozngvveozqcxgfecir.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwb3puZ3Z2ZW96cWN4Z2ZlY2lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5NTUxMTMsImV4cCI6MjA5MjUzMTExM30.YjjYxFtrDSivq3ss33AHjHS7SxnyRA4n0HDzZfmgWNs';

const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
